
[workspace]
members = [
  "packages/blitz-traits",
  "packages/blitz-dom", 
  "packages/blitz-html",
  "packages/blitz-net",
  "packages/blitz-renderer-vello",
  "packages/blitz-shell",
  "packages/dioxus-native",
  "packages/stylo_taffy",
  "apps/wpt",
  "apps/readme",
]
resolver = "2"

[workspace.package]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# Servo dependencies
style = { git = "https://github.com/nicoburns/stylo", rev = "61c02a463", package = "style" } # u64-opaque-element
style_config = { git = "https://github.com/nicoburns/stylo", rev = "61c02a463", package = "style_config" } # u64-opaque-element
style_traits = { git = "https://github.com/nicoburns/stylo", rev = "61c02a463", package = "style_traits" } # u64-opaque-element
style_dom = { git = "https://github.com/nicoburns/stylo", rev = "61c02a463", package = "dom" } # u64-opaque-element
selectors = { git = "https://github.com/nicoburns/stylo", rev = "61c02a463", package = "selectors" } # u64-opaque-element
markup5ever = "0.14" # needs to match stylo markup5ever version
html5ever = "0.29" # needs to match stylo markup5ever version
xml5ever = "0.20" # needs to match stylo markup5ever version
euclid = "0.22"
string_cache = "0.8.7"
atomic_refcell = "0.1.13"
app_units = "0.7.5"

# DioxusLabs dependencies
dioxus = { version = "0.6" }
dioxus-core = { version = "0.6" }
dioxus-html = { version = "0.6" }
dioxus-cli-config = { version = "0.6" }
dioxus-devtools = { version = "0.6" }
taffy = { git = "https://github.com/dioxuslabs/taffy", rev = "63f4adebf", default-features = false, features = ["std", "flexbox", "grid", "block_layout", "content_size"] }

# Linebender + WGPU
peniko = "0.2"
vello = { version = "0.3", features = [ "wgpu" ] }
parley = { version = "0.2", git = "https://github.com/linebender/parley", rev = "4ef147da7909f44827c78aa31b76f184152ab382" }
wgpu = "22.1.0"

# SVG dependencies
vello_svg = "0.5"
usvg = "0.44.0"

# Windowing & Input
raw-window-handle = "0.6.0"
winit = { version = "0.30.2", features = ["rwh_06"] }
accesskit_winit = "0.21.1"
accesskit = "0.15.0"
muda = "0.11.5"
arboard = "3.4.1"
keyboard-types = "0.7"

# IO & Networking
url = "2.5.0"
http = "1.1.0"
data-url = "0.3.1"
tokio = "1.25.0"
reqwest = "0.12.7"
ureq = "2.9"

# Media & Decoding
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "gif", "webp"] }
woff = "0.3.3"
html-escape = "0.2.13"

# Other dependencies
rustc-hash = "1.1.0"
bytes = "1.7.1"
slab = "0.4.9"
tracing = "0.1.40"
futures-util = "0.3.30"
futures-intrusive = "0.5.0"
thiserror = "1.0.63"


# This is a "virtual package"
# It is not meant to be published, but is used so "cargo run --example XYZ" works properly
[package]
name = "blitz-examples"
version = "0.0.1"
authors = ["Jonathan Kelley"]
edition = "2021"
description = "Top level crate for Blitz"
license = "MIT OR Apache-2.0"
keywords = ["dom", "ui", "gui", "react", "wasm"]
rust-version = "1.70.0"
publish = false

[profile.dev.package."*"]
opt-level = 2

[profile.sizeopt]
inherits = "release"
opt-level = "z"
debug = false
lto = true
codegen-units = 1
strip = true
incremental = false

# Need to force specific versions of these dependencies
[dev-dependencies]
# webrender = "0.61.0"
# mozbuild = "0.1.0"
blitz-dom = { path = "./packages/blitz-dom" }
blitz-html = { path = "./packages/blitz-html" }
blitz-traits = { path = "./packages/blitz-traits" }
blitz-renderer-vello = { path = "./packages/blitz-renderer-vello" }
blitz-shell = { path = "./packages/blitz-shell" }
blitz-net = { path = "./packages/blitz-net" }
dioxus-native = { path = "./packages/dioxus-native", features = ["tracing"] }
dioxus = { workspace = true }
euclid = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
ureq = { workspace = true }
image = { workspace = true }
png = "0.17"
env_logger = "0.11"
tracing-subscriber = "0.3"

# [patch.crates-io]
# [patch."https://github.com/dioxuslabs/taffy"]
# taffy = { path = "../taffy" }

# [patch."https://github.com/nicoburns/parley"]
# parley = { path = "../parley/parley" }
# fontique = { path = "../parley/fontique" }

# # need to match the patching of
# [patch."https://github.com/servo/webrender"]
# webrender_api = { git = "https://github.com/servo/servo", rev = "95931de" }
# webrender = { git = "https://github.com/servo/servo", rev = "95931de" }

# [patch.crates-io]
# webrender_api = { git = "https://github.com/servo/servo", rev = "95931de" }
# webrender = { git = "https://github.com/servo/servo", rev = "95931de" }


# webrender_api = { path = "../../../servo/third_party/webrender/webrender_api" }
# webrender = { path = "../../../servo/third_party/webrender/webrender" }
# webrender_api = { path = "../../../servo/third_party/webrender/webrender_api" }
# webrender = { path = "../../../servo/third_party/webrender/webrender" }

# [patch."https://github.com/servo/webrender"]
# webrender_api = { path = "../servo/third_party/webrender/webrender_api" }
# webrender = { path = "../servo/third_party/webrender/webrender" }

# [patch.crates-io]
# webrender_api = { path = "../servo/third_party/webrender/webrender_api" }
# webrender = { path = "../servo/third_party/webrender/webrender" }
