[package]
name = "counter"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
dioxus-native = { path = "../../packages/dioxus-native", default-features = false }
dioxus = { version = "0.6", default-features = false, features = ["html", "hooks", "macro", "signals"] }

# Disable unicode URL support
# See https://github.com/hsivonen/idna_adapter
idna_adapter = "=1.0.0"