[package]
name = "blitz-renderer-vello"
description = "Blitz renderer using vello"
version = "0.1.0-alpha.1"
homepage = "https://github.com/dioxuslabs/blitz"
repository = "https://github.com/dioxuslabs/blitz"
documentation = "https://docs.rs/blitz-renderer-vello"
license.workspace = true
edition = "2024"

[features]
default = ["tracing", "svg"]
tracing = ["dep:tracing"]
svg = ["dep:vello_svg", "blitz-dom/svg"]

[dependencies]
blitz-traits = { version = "0.1.0-alpha.1", path = "../blitz-traits" }
blitz-dom = {version = "0.1.0-alpha.1",  path = "../blitz-dom", default-features = false }
style = { workspace = true, features = ["servo"] }
euclid = { workspace = true }
taffy = { workspace = true }
parley = { workspace = true }
tracing = { workspace = true, optional = true }
color = { workspace = true }
vello = { workspace = true }
vello_svg = { workspace = true, optional = true }
wgpu = { workspace = true }
raw-window-handle = { workspace = true }
image = { workspace = true }
futures-intrusive = { workspace = true }
pollster = { workspace = true }
