[package]
name = "blitz-net"
description = "Blitz networking"
version = "0.1.0-alpha.1"
homepage = "https://github.com/dioxuslabs/blitz"
repository = "https://github.com/dioxuslabs/blitz"
documentation = "https://docs.rs/blitz-net"
license.workspace = true
edition = "2024"

[dependencies]
blitz-traits = { version = "0.1.0-alpha.1", path = "../blitz-traits" }
tokio = { workspace = true }
reqwest = { workspace = true }
data-url = { workspace = true }
thiserror = { workspace = true }
